first commit
UTokyo-Tech-Club/curriculum_4_seiji-kakitsu pull request #19
Opened 2023-10-15 08:20 UTC by sijut0123

2023-10-15 12:44 UTC, nockoy requested changes

2023-10-15 12:44 UTC, nockoy commented on react-to-go/api/.env
> +export MYSQL_DATABASE=test_database
.envファイルはパスワードなどを記しているため、githubで公開するのは危険です。
.gitignoreにパスを追加して公開しないようにするなどしましょう。

2023-10-15 12:44 UTC, nockoy commented on react-to-go/api/main.go
> +		if len(requestData.Name) > 50 {
lenで返されるのはバイト長なので、名前を全て漢字を入力した場合であれば17字しか入力していなくてもバリデーションに引っかかってしまいます。
試しに「一二三四五六七八九〇一二三四五六七八九〇一二三四五六七」のような文字列を送信すると登録できないことがわかると思います。

2023-10-16 03:56 UTC, sijut0123 commented
.gitignoreファイルに.envを入れました
また、unicode/utf8パッケージのRuneCountInString関数を使って文字数をカウントするように変更しました。

2023-10-16 04:03 UTC, nockoy commented
LGTM！マージして大丈夫です！

2023-10-16 04:37 UTC, merged